#!/bin/bash

rootdir=$PWD;
target=/mnt/safe/test-generator

function views {
    inotifywait -rm -e modify -e create $rootdir/app/templates/views |
        while read file; do
            echo $file;
            cp -rf $rootdir/app/templates/views $target/src
        done
}

function styles {
    inotifywait -rm -e modify -e create $rootdir/app/templates/styles |
        while read file; do
            echo $file;
            cp -rf $rootdir/app/templates/styles $target/src
        done
}

function app-gruntfile {
    inotifywait -m -e modify -e create $rootdir/app/templates |
        while read file; do
            php -r 'list($path, $event, $filename) = explode(" ", "{$file"); echo $path . $event . $filename;'
        done

}
$*