tmp: .tmp

src:
  views: src/views
  styles: src/styles
  scripts: src/scripts
  tasks: src/tasks

build:
  dir: build
  assets: build/assets
  bower: build/assets/plugins

dist:
  dir: dist
  assets: dist/assets
