---
layout: page
title: <%= title %>
minify_content: false
navigation:
  - name: Home
    link: /
    icon: fa fa-home

  - name: Overview
    link: /github-jquery-widgets
    icon: fa fa-dashboard

  <% if(demo){ %>
  - name: Demonstration
    link: /github-jquery-widgets/demo
    icon: fa fa-forward
  <% } %>
  - name: Coverage
    link: /github-jquery-widgets/coverage
    icon: fa fa-code

---
